version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres_fastapi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  adminer:
    image: adminer
    container_name: adminer_fastapi
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge
